### ISSUE TITLE
Non-determinism when deploying worker from a PR

### ISSUE THREAD

**Issue by joepvd** [travis-ci/terraform-config#399]
There have been unpredictable results when running `make plan` to try and test a new worker version in staging.

`bin/generate-latest-docker-image-tags` does not know what the newest docker tag is for the most recent worker. Input data from the tags from docker hub:

```
v3.6.0-14-gc9f6bda
v3.6.0-14-g592d662
v3.6.0-13-g1c1f9ec
v3.6.0-12-g76c1dc7
v3.6.0-11-gca14cdd
```

On some runs, the first `v3.6.0-14` will be selected, and on some runs, the second `v3.6.0-14`. One of the `-14-`-s is from a PR (not yet merged in master).

**Comment by bogdanap** [comment]
After looking into this with Joep, we've discovered that this is caused by the `generate-latest-docker-image-tags` script, which drops the commit hash and only looks at the release numbers.
While this is indeed unpredictable behaviour, I don't think the effort of fixing it is necessarily worth it since this only happens for parallel branches and only on staging (where we rely on the latest docker image instead of a specific version). 

Furthermore, even fixing it to always retrieve the latest tag would still cause issues in the parallel branches case because people might not be aware someone else might have built a new image and deploy that one instead of their own. 

What I'd recommend in this case is document worker staging deployments maybe, but I'm also curious to hear other opinions. 😄

**Comment by joepvd** [comment]
Workaround documented.
